### ISSUE TITLE
Only works with english language

### ISSUE THREAD

**Issue by Tcm0** [luigoalma/nitpic3d#3]
The game crashes with a normal error if the language is set to another language than english (I tested german). It would be helpful to add this information to the readme or to fix it. Works fine if the language is changed to english.

**Comment by luigoalma** [comment]
Oh really? I'll look into it. I didn't think of the other languages, the game may have allocated different lengths of data for other things. That would affect positioning of SAVE in memory relative to an object that is used reach out to ROP.
It's likely data size differences, I might end up just warning to set language to english before launching, but I'll check anyhow.

**Comment by luigoalma** [comment]
Sorry for leaving this one a bit on the dark. I've gotten the values I need to make work on other languages. Asides English, EUR version has four more languages, and USA has two more. I've gotten the necessary addresses for all of them.
I might take a bit to actually get it public now, mainly for adding it to the installer the ability to select language, as well adjust building `SAVEDATA` for all the languages and regions.
Save in memory was allocated elsewhere for each of all different languages, that means I need a `SAVEDATA` per each, has to be built per each address.
Also the address of the object used to break out of bounds, need to ensure overflow value is proper.

**Comment by luigoalma** [comment]
Now fixed with 0abbd9b and provided installation with v1.1.0 release.
